name: nft
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  bip39: ^1.0.6
  ethers: ^0.0.1+3
  freezed_annotation: ^2.2.0
  http: ^0.13.6
  web3dart: ^2.6.1
  web_socket_channel: ^2.4.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  lints: ^2.0.0
  test: ^1.21.0
